services:

  postgres:
    image: postgres
    container_name: auth_api_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./dockerDB/auth.sql:/docker-entrypoint-initdb.d/auth.sql
    ports:
      - 5432:5432

  app:
    image: auth_api:latest
    container_name: auth_api
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres